name: Do things every 5 minutes
on:
#  schedule:
#    - cron: "*/5 * * * *"
  workflow_dispatch:
    
    
# Instead download current date of NOAA AWS file at correct date/time like:
# https://noaa-gfs-bdp-pds.s3.amazonaws.com/index.html#gfs.20230210/18/atmos/
# https://noaa-gfs-bdp-pds.s3.amazonaws.com/index.html#gfs.YYYYMMDD/HH/atmos/
jobs:
  wget:
    runs-on: ubuntu-latest
    steps:
    - name: wget
      uses: wei/wget@v1
      with:
        args: -O sample.html https://httpbin.org/html
        
        
# job2
# parse GRIB file into simple JSON format

# job 3
# save JSON file to local repo
