name: Do things every 5 minutes
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
    
    
jobs:
  wget:
    runs-on: ubuntu-latest
    steps:
    - name: wget
      uses: wei/wget@v1
      with:
        args: -O sample.html https://httpbin.org/html
